service: gateway

plugins:
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  #stage: production
  region: us-east-1
  memorySize: 2048

custom:
  serverless-offline:
    httpPort: 4001


functions:
  node:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'